name: dl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch==2.2.0
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - scikit-learn
  - joblib
  - matplotlib
  - pip
  - pip:
      - catboost==1.2.3